'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="SOLUCIONES_INTERNAS")>  _
Partial Public Class DataS_Interno_Vistas
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definiciones de métodos de extensibilidad"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.SOLUCIONES_INTERNAS.My.MySettings.Default.SOLUCIONES_INTERNASConnectionString1, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property VistaTareas() As System.Data.Linq.Table(Of VistaTareas)
		Get
			Return Me.GetTable(Of VistaTareas)
		End Get
	End Property
	
	Public ReadOnly Property Vista_Tarea_x_Colaborador() As System.Data.Linq.Table(Of Vista_Tarea_x_Colaborador)
		Get
			Return Me.GetTable(Of Vista_Tarea_x_Colaborador)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.VistaTareas")>  _
Partial Public Class VistaTareas
	
	Private _SEC_id_sector As System.Nullable(Of Integer)
	
	Private _SEC_nombre_sector As String
	
	Private _COL_id_colaborador As Integer
	
	Private _COL_nombre_col As String
	
	Private _TAR_id_tarea As Integer
	
	Private _TAR_detalle_tarea As String
	
	Private _TAR_fecha As System.Nullable(Of Date)
	
	Private _ORT_id_orden_trabajo As System.Nullable(Of Integer)
	
	Private _ORT_numero_ot As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEC_id_sector", DbType:="Int")>  _
	Public Property SEC_id_sector() As System.Nullable(Of Integer)
		Get
			Return Me._SEC_id_sector
		End Get
		Set
			If (Me._SEC_id_sector.Equals(value) = false) Then
				Me._SEC_id_sector = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEC_nombre_sector", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SEC_nombre_sector() As String
		Get
			Return Me._SEC_nombre_sector
		End Get
		Set
			If (String.Equals(Me._SEC_nombre_sector, value) = false) Then
				Me._SEC_nombre_sector = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COL_id_colaborador", DbType:="Int NOT NULL")>  _
	Public Property COL_id_colaborador() As Integer
		Get
			Return Me._COL_id_colaborador
		End Get
		Set
			If ((Me._COL_id_colaborador = value)  _
						= false) Then
				Me._COL_id_colaborador = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COL_nombre_col", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property COL_nombre_col() As String
		Get
			Return Me._COL_nombre_col
		End Get
		Set
			If (String.Equals(Me._COL_nombre_col, value) = false) Then
				Me._COL_nombre_col = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_id_tarea", DbType:="Int NOT NULL")>  _
	Public Property TAR_id_tarea() As Integer
		Get
			Return Me._TAR_id_tarea
		End Get
		Set
			If ((Me._TAR_id_tarea = value)  _
						= false) Then
				Me._TAR_id_tarea = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_detalle_tarea", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property TAR_detalle_tarea() As String
		Get
			Return Me._TAR_detalle_tarea
		End Get
		Set
			If (String.Equals(Me._TAR_detalle_tarea, value) = false) Then
				Me._TAR_detalle_tarea = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_fecha", DbType:="Date")>  _
	Public Property TAR_fecha() As System.Nullable(Of Date)
		Get
			Return Me._TAR_fecha
		End Get
		Set
			If (Me._TAR_fecha.Equals(value) = false) Then
				Me._TAR_fecha = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORT_id_orden_trabajo", DbType:="Int")>  _
	Public Property ORT_id_orden_trabajo() As System.Nullable(Of Integer)
		Get
			Return Me._ORT_id_orden_trabajo
		End Get
		Set
			If (Me._ORT_id_orden_trabajo.Equals(value) = false) Then
				Me._ORT_id_orden_trabajo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORT_numero_ot", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property ORT_numero_ot() As String
		Get
			Return Me._ORT_numero_ot
		End Get
		Set
			If (String.Equals(Me._ORT_numero_ot, value) = false) Then
				Me._ORT_numero_ot = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Vista_Tarea_x_Colaborador")>  _
Partial Public Class Vista_Tarea_x_Colaborador
	
	Private _Expr1 As Integer
	
	Private _COL_nombre_col As String
	
	Private _TAR_id_tarea As Integer
	
	Private _TAR_tiempo_estimado As System.Nullable(Of Integer)
	
	Private _TAR_tiempo_real As System.Nullable(Of Integer)
	
	Private _ORT_id_orden_trabajo As System.Nullable(Of Integer)
	
	Private _TAR_hora_fin As String
	
	Private _TAR_carga_horaria As System.Nullable(Of Integer)
	
	Private _TAR_detalle_tarea As String
	
	Private _TAR_observaciones As String
	
	Private _TAR_fecha As System.Nullable(Of Date)
	
	Private _SEC_id_sector As Integer
	
	Private _SEC_nombre_sector As String
	
	Private _ORT_numero_ot As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Expr1", DbType:="Int NOT NULL")>  _
	Public Property Expr1() As Integer
		Get
			Return Me._Expr1
		End Get
		Set
			If ((Me._Expr1 = value)  _
						= false) Then
				Me._Expr1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COL_nombre_col", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property COL_nombre_col() As String
		Get
			Return Me._COL_nombre_col
		End Get
		Set
			If (String.Equals(Me._COL_nombre_col, value) = false) Then
				Me._COL_nombre_col = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_id_tarea", DbType:="Int NOT NULL")>  _
	Public Property TAR_id_tarea() As Integer
		Get
			Return Me._TAR_id_tarea
		End Get
		Set
			If ((Me._TAR_id_tarea = value)  _
						= false) Then
				Me._TAR_id_tarea = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_tiempo_estimado", DbType:="Int")>  _
	Public Property TAR_tiempo_estimado() As System.Nullable(Of Integer)
		Get
			Return Me._TAR_tiempo_estimado
		End Get
		Set
			If (Me._TAR_tiempo_estimado.Equals(value) = false) Then
				Me._TAR_tiempo_estimado = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_tiempo_real", DbType:="Int")>  _
	Public Property TAR_tiempo_real() As System.Nullable(Of Integer)
		Get
			Return Me._TAR_tiempo_real
		End Get
		Set
			If (Me._TAR_tiempo_real.Equals(value) = false) Then
				Me._TAR_tiempo_real = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORT_id_orden_trabajo", DbType:="Int")>  _
	Public Property ORT_id_orden_trabajo() As System.Nullable(Of Integer)
		Get
			Return Me._ORT_id_orden_trabajo
		End Get
		Set
			If (Me._ORT_id_orden_trabajo.Equals(value) = false) Then
				Me._ORT_id_orden_trabajo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_hora_fin", DbType:="VarChar(10)")>  _
	Public Property TAR_hora_fin() As String
		Get
			Return Me._TAR_hora_fin
		End Get
		Set
			If (String.Equals(Me._TAR_hora_fin, value) = false) Then
				Me._TAR_hora_fin = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_carga_horaria", DbType:="Int")>  _
	Public Property TAR_carga_horaria() As System.Nullable(Of Integer)
		Get
			Return Me._TAR_carga_horaria
		End Get
		Set
			If (Me._TAR_carga_horaria.Equals(value) = false) Then
				Me._TAR_carga_horaria = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_detalle_tarea", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property TAR_detalle_tarea() As String
		Get
			Return Me._TAR_detalle_tarea
		End Get
		Set
			If (String.Equals(Me._TAR_detalle_tarea, value) = false) Then
				Me._TAR_detalle_tarea = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_observaciones", DbType:="VarChar(200) NOT NULL", CanBeNull:=false)>  _
	Public Property TAR_observaciones() As String
		Get
			Return Me._TAR_observaciones
		End Get
		Set
			If (String.Equals(Me._TAR_observaciones, value) = false) Then
				Me._TAR_observaciones = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAR_fecha", DbType:="Date")>  _
	Public Property TAR_fecha() As System.Nullable(Of Date)
		Get
			Return Me._TAR_fecha
		End Get
		Set
			If (Me._TAR_fecha.Equals(value) = false) Then
				Me._TAR_fecha = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEC_id_sector", DbType:="Int NOT NULL")>  _
	Public Property SEC_id_sector() As Integer
		Get
			Return Me._SEC_id_sector
		End Get
		Set
			If ((Me._SEC_id_sector = value)  _
						= false) Then
				Me._SEC_id_sector = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEC_nombre_sector", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SEC_nombre_sector() As String
		Get
			Return Me._SEC_nombre_sector
		End Get
		Set
			If (String.Equals(Me._SEC_nombre_sector, value) = false) Then
				Me._SEC_nombre_sector = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORT_numero_ot", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property ORT_numero_ot() As String
		Get
			Return Me._ORT_numero_ot
		End Get
		Set
			If (String.Equals(Me._ORT_numero_ot, value) = false) Then
				Me._ORT_numero_ot = value
			End If
		End Set
	End Property
End Class
